---
- name: "import RHEL tasks"
  ansible.builtin.include_tasks: rhel/main.yml
  when: ansible_os_family == 'RedHat'

- name: "import Debian tasks"
  ansible.builtin.include_tasks: debian/main.yml
  when: ansible_os_family == 'Debian'
