---
# @meta author: Vincent Fricou
# @meta description: Deploy and/or configure mariadb server
# @tag install # Install and configure mariadb server
# @tag configure # Configure mariadb server and logrotate
# @tag backup # Perform backup (dump) task

- block:
    - name: "import validator tasks"
      ansible.builtin.import_tasks: validator/main.yml
    - name: "import prerequisites tasks"
      ansible.builtin.import_tasks: prerequisites/main.yml
  tags:
    - always

- block:
    - name: "import install tasks"
      ansible.builtin.import_tasks: install/main.yml

    - name: "INCLUDE => RHEL mariadb | preconfigure tasks"
      ansible.builtin.include_tasks: mariadb/preconfigure.yml
  tags:
    - install

- block:
    - name: "INCLUDE => RHEL mariadb | configure tasks"
      ansible.builtin.include_tasks: mariadb/configure.yml

    - name: "import logrotate configuration tasks"
      ansible.builtin.import_tasks: logrotate/main.yml

    - name: "import mariadb post installation tasks"
      ansible.builtin.import_tasks: mariadb/postconfigure.yml
  tags:
    - install
    - configure

- name: "import backup tasks"
  ansible.builtin.import_tasks: mariadb/backup/main.yml
  tags:
    - backup

- name: "INCLUDE => USER mariadb | user tasks"
  ansible.builtin.import_tasks: mariadb/user/main.yml
  tags:
    - user
