---
- name: "import RHEL tasks"
  ansible.builtin.include_tasks: rhel/main.yml
  vars:
    config_server: "{{ rhel['path'] }}/{{ mariadb['path']['server'] }}"
    config_network: "{{ rhel['path'] }}/{{ mariadb['path']['network'] }}"
    config_custom: "{{ rhel['path'] }}/{{ mariadb['path']['custom'] }}"
  when: ansible_os_family == 'RedHat'

- name: "import Debian tasks"
  ansible.builtin.include_tasks: debian/main.yml
  vars:
    config_server: "{{ debian['path'] }}/{{ mariadb['path']['server'] }}"
    config_network: "{{ debian['path'] }}/{{ mariadb['path']['network'] }}"
    config_custom: "{{ debian['path'] }}/{{ mariadb['path']['custom'] }}"
  when: ansible_os_family == 'Debian'
