---
- name: "import RHEL tasks"
  ansible.builtin.include_tasks: rhel/main.yml
  when: ansible_distribution == 'Rocky' or
        ansible_distribution == 'RedHat' or
        ansible_distribution == 'AlmaLinux'

- name: "import Debian tasks"
  ansible.builtin.include_tasks: debian/main.yml
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
