---
- name: 'processing | user_creation | manage user {{ user.key }}'
  community.mysql.mysql_user:
    name: "{{ user.key }}"
    host: "{{ user['value']['host'] }}"
    password: "{{ user['value']['password'] }}"
    login_unix_socket: "{{ socket_path }}"
    check_implicit_admin: yes
    state: "{{ user['value']['state'] }}"
    priv: "{{ user['value']['privileges'] }}"
