---
- name: "INCLUDE => RHEL logrotate | configure"
  ansible.builtin.include_tasks: configure.yml
  vars:
    config_default_path: '/etc/my.cnf'
  when: ansible_os_family == 'RedHat'

- name: "INCLUDE => DEBIAN logrotate | configure"
  ansible.builtin.include_tasks: configure.yml
  vars:
    config_default_path: '/etc/mysql/debian.cnf'
  when: ansible_os_family == 'Debian'
