---
- name: "import RHEL tasks"
  ansible.builtin.include_tasks: rhel/main.yml
  when: (ansible_distribution == 'Rocky' and ansible_distribution_major_version|int >= 8) or
        (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8) or
        (ansible_distribution == 'AlmaLinux' and ansible_distribution_major_version|int >= 8)
