---
- name: "mariadb | postconfigure | systemd | update systemd unit with override"
  ansible.builtin.template:
    src: systemd/mariadb_override.j2
    dest: /etc/systemd/system/mariadb.service.d/override.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart mariadb
