---
- name: "mariadb | backup | perform {{ db.key }} database dump"
  community.mysql.mysql_db:
    login_host: '127.0.0.1'
    config_file: /root/.my.backup.cnf
    state: dump
    name: '{{ db.key }}'
    target: '{{ mariadb_backup_path }}/{{ db.key }}.{{ ansible_date_time.weekday }}.sql'
    dump_extra_args: --single-transaction --compact --order-by-primary --add-drop-table
  when:
    - '"information_schema" not in db.key'
